apiVersion: v1
kind: Pod
metadata:
  name: helloworld.example.com
  labels:
    app: helloworld
spec:
  containers:
    - name: k8s-demo
    - image: crccheck/hello-world
    - ports:
      - containerPort: 8000